name: Daily Commit

on:
  schedule:
    - cron: "0 6 * * *" # هر روز ساعت 6 صبح UTC (معادل 10:30 صبح ایران)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Make a change
        run: |
          echo "$(date) - commit by GitHub Actions" >> log.txt

      - name: Commit changes
        run: |
          git config user.name "Matin-Talkhabi"
          git config user.email "matintalkhabidev@gmail.com"
          git add .
          git commit -m "daily commit - $(date)" || echo "nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
